# Generated by Django 4.1.3 on 2022-11-08 13:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=50, verbose_name="Nombre del cliente"),
                ),
                ("fecha", models.DateField(verbose_name="Fecha de la reserva")),
                ("hora", models.TimeField(verbose_name="Hora de la reserva")),
                (
                    "telefono",
                    models.CharField(max_length=9, verbose_name="Telefono del cliente"),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("R", "RESERVADO"),
                            ("C", "COMPLETADA"),
                            ("A", "ANULADA"),
                            ("N", "NO ASISTEN"),
                        ],
                        default="R",
                        max_length=20,
                        verbose_name="Estado de la reserva",
                    ),
                ),
                (
                    "qty_personas",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(15),
                        ],
                        verbose_name="Cantidad de personas",
                    ),
                ),
                (
                    "comentario",
                    models.TextField(blank=True, null=True, verbose_name="Observación"),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
